;全局配置
[global]
;配置是否烧写私有数据，烧写到private分区，1:烧写，0:不烧写
valid=0
;配置私有数据烧写方式，fat或者struct，默认是fat的文件系统。
type=fat
;配置私有数据分区容量，根据分区表中private分区大小来配置
fssize=16M
;配置私有数据总量，总共需要烧写的总数量
count=1000
;此项非配置项，根据使用情况动态记录数据已使用情况
used=1
;配置文件系统方式时数据的根目录(可选)
rootdir=/
;节点配置开始-------------------------------
;项名称，标识一个节点
[snum]
;数据增长模式，配置私有数据自动增长模式，支持十进制(10)和十六进制(16)
patterns=16
;起始地址，配置私有数据的起始值，增长步长都为1
base=0000000000000000000
;配置项所在子目录（可选）
subdir=ULI/factory
;此项非配置项，根据使用情况动态更新当前烧录的值，cur = base + used
cur=0000000000000000001

[wifi_mac]
patterns=16
base=00:10:03:46:33:00
subdir=ULI/factory
cur=00:10:03:46:33:01

[bt_mac]
patterns=16
base=11:10:03:46:33:00
subdir=ULI/factory
cur=11:10:03:46:33:01
;节点配置结束-------------------------------